TicketManagementSystem/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketManagementSystem.Core.Models;
using TicketManagementSystem.Data;

namespace TicketManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public static readonly string BITOREQNAME = "Bitoreq";

        public ProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Projects.Include(p => p.Company).Include(p => p.Developer1User).Include(p => p.Developer2User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Company)
                .Include(p => p.Developer1User)
                .Include(p => p.Developer2User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult AddProject()
        {
            IEnumerable<SelectListItem> developers = GetDevelopersList();
            
            ViewData["CompanyName"] = new SelectList(_context.Companies.Where(c => c.CompanyName != BITOREQNAME), "Id", "CompanyName");
            ViewData["Developer1"] = developers;
            ViewData["Developer2"] = developers;
            return View();
        }

        private IEnumerable<SelectListItem> GetDevelopersList()
        {
            var developerRole = _context.Roles.Where(r => r.Name == "Developer").FirstOrDefault().Id;
            var developersId = _context.UserRoles.Where(ur => ur.RoleId == developerRole).Select(u => u.UserId).ToList();

            IEnumerable<SelectListItem> developers = _context.Users.Where(u => developersId.Contains(u.Id)).Select(i => new SelectListItem()
            {
                Text = i.UserName,
                Value = i.Id
            });
            
            return developers;
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProject([Bind("Id,CompanyId,Name,Developer1,Developer2,ReleaseDate,LastUpdate,Description,SystemsUsed")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            IEnumerable<SelectListItem> developers = GetDevelopersList();

            ViewData["CompanyName"] = new SelectList(_context.Companies, "Id", "CompanyName", project.CompanyId);
            ViewData["Developer1"] = developers;
            ViewData["Developer2"] = developers;
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.Include(c => c.Company).Where(p => p.Id == id).FirstOrDefaultAsync();
            
            if (project == null)
            {
                return NotFound();
            }

            var tickets = _context.Tickets.Where(t => t.ProjectId == id).Count();

            if (tickets == 0)
            {
                ViewData["company"] = "show";
            }
            else
            {
                ViewData["company"] = "hide";
            }


            IEnumerable<SelectListItem> developers = GetDevelopersList();

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "CompanyAbbr", project.CompanyId);
            ViewData["Developer1"] = developers;
            ViewData["Developer2"] = developers;

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Developer1,Developer2,ReleaseDate,LastUpdate,Description,SystemsUsed")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            IEnumerable<SelectListItem> developers = GetDevelopersList();

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "CompanyAbbr", project.CompanyId);
            ViewData["Developer1"] = developers;
            ViewData["Developer2"] = developers;
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Company)
                .Include(p => p.Developer1User)
                .Include(p => p.Developer2User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            var anytickets= _context.Tickets.Where(t=>t.ProjectId==id).Count();
            

            if (anytickets == 0)
            {
                ViewData["formhide"] = "Show";
            }
            else
            {
                ViewData["formhide"] = "Hide";
            }




            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult CheckLastUpdate(DateTime ReleaseDate, DateTime LastUpdate)
        {
            if (LastUpdate < ReleaseDate)
            {
                return Json($"{LastUpdate} är inte giltig. Borde vara större än släppdatum.");
            }

            return Json(true);
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.Id == id);
        }
    }
}

TicketManagementSystem/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Text.Encodings.Web;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using TicketManagementSystem.Core.Models;
using TicketManagementSystem.Core.ViewModels;
using TicketManagementSystem.Data;
using System.Diagnostics;
using TicketManagementSystem.Models;

namespace TicketManagementSystem.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext _context;
        private static ApplicationUser loggedInUser;
        private static IEnumerable<ApplicationUser> confirmedCustomers;
        private List<ApplicationUser> ticketProjectDevelopers;        
        private readonly IEmailSender _emailSender;

        public TicketsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            this.userManager = userManager;
            _emailSender = emailSender;
        }

        // GET: Tickets
        [Authorize]
        public async Task<IActionResult> Index(string sortOrder, List<TicketIndexViewModel> model)
        {
            //var applicationdbcontext = _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project);
            // return View(await applicationdbcontext.ToListAsync());

            var loggedInUser = await userManager.GetUserAsync(User);

            // List all the result 
            if (User.IsInRole("Admin"))
            {
                model = await TicketViewModelAdmin(model);
            }
            else if(User.IsInRole("Developer"))
            {
                model = await TicketViewModelDeveloper(model, loggedInUser);
            }
            else
            {
                model = await TicketViewModelCustomer(model, loggedInUser);
            }

            if (User.IsInRole("Developer") || User.IsInRole("Admin"))
            {
                ViewData["Companies"] = new SelectList(_context.Companies, "Id", "CompanyName");
                ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name");
            }

            else if (User.IsInRole("Customer"))
            {
                //loggedInUser = await userManager.GetUserAsync(User);
                ViewData["ProjectId"] = new SelectList(_context.Projects.Where(g => g.CompanyId == loggedInUser.CompanyId), "Id", "Name");
            }

            // Sort by attributes in the list
            //model = SortList(sortOrder, model);
            return View(model);
        }

        // Index for Customer Company Tickets  
        public async Task<IActionResult> IndexCompanyTickets(string sortOrder, List<TicketIndexViewModel> model, string title, int? statusSearch, int? customerPriority, int? priorities)
        {
            var loggedInUser = await userManager.GetUserAsync(User);

            ViewData["ProjectId"] = new SelectList(_context.Projects.Where(g => g.CompanyId == loggedInUser.CompanyId), "Id", "Name");

            // List all the result by Company
            model = await _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project)
                        .Where(u => u.CreatedUser.CompanyId == loggedInUser.CompanyId)
                        .Select(s => new TicketIndexViewModel
                        {
                            Id = s.Id,
                            RefNo = s.RefNo,
                            Title = s.Title,
                            Status = s.Status,
                            ProjectName = s.Project.Name,
                            CustomerPriority = s.CustomerPriority,
                            RealPriority = s.RealPriority,
                            DueDate = s.DueDate,
                            UserEmail = s.AssignedUser.Email,
                            HoursSpent = s.HoursSpent
                        })
                        .ToListAsync();


            // Sort by attributes in the list
            // model = SortList(sortOrder, model);
            return View(model);
        }

        // Customer tickets ViewModel and List all the result by UserId
        private async Task<List<TicketIndexViewModel>> TicketViewModelCustomer(List<TicketIndexViewModel> model, ApplicationUser loggedInUser)
        {
            model = await _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project)
                    .Where(u => u.CreatedBy == loggedInUser.Id)
                    .Select(s => new TicketIndexViewModel
                    {
                        Id = s.Id,
                        RefNo = s.RefNo,
                        Title = s.Title,
                        Status = s.Status,
                        ProjectName = s.Project.Name,
                        CustomerPriority = s.CustomerPriority,
                        RealPriority = s.RealPriority,
                        DueDate = s.DueDate,
                        UserEmail = s.AssignedUser.Email,
                       
                    })
                    .ToListAsync();

            return model;
        }

        // Admin tickets ViewModel and List all the result and not show Draft status and Closed status
        private async Task<List<TicketIndexViewModel>> TicketViewModelAdmin(List<TicketIndexViewModel> model)
        {

            model = await _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project)
            .Where(s => s.Status != Status.Utkast && s.Status != Status.Avslutat)
            .Select(s => new TicketIndexViewModel
            {
                Id = s.Id,
                RefNo = s.RefNo,
                Title = s.Title,
                Status = s.Status,
                ProjectName = s.Project.Name,
                CompanyName = s.Project.Company.CompanyName,
                CustomerPriority = s.CustomerPriority,
                RealPriority = s.RealPriority,
                DueDate = s.DueDate,
                UserEmail = s.AssignedUser.Email,
                HoursSpent = s.HoursSpent,
                ResponseType = s.ResponseType
            })
                .ToListAsync();
            
                return model;
        }

        private async Task<List<TicketIndexViewModel>> TicketViewModelDeveloper(List<TicketIndexViewModel> model, ApplicationUser loggedInUser)
        {   
                model = await _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project)
               .Where(u => u.AssignedTo == loggedInUser.Id)
               .Select(s => new TicketIndexViewModel
               {
                   Id = s.Id,
                   RefNo = s.RefNo,
                   Title = s.Title,
                   Status = s.Status,
                   ProjectName = s.Project.Name,
                   CompanyName = s.Project.Company.CompanyName,
                   CustomerPriority = s.CustomerPriority,
                   RealPriority = s.RealPriority,
                   DueDate = s.DueDate,
                   UserEmail = s.AssignedUser.Email,
                   HoursSpent = s.HoursSpent,
                   ResponseType = s.ResponseType
               })
                   .ToListAsync();

            return model;
        }
        //Filter by Title, Status and Priority
        public async Task<IActionResult> Filter(string companySearch, string projectSearch, string title, int? statusSearch, int? customerPriority, int? adminPriority, int? priorities, List<TicketIndexViewModel> model, List<TicketIndexViewModel> model2, string sortOrder, string currentFilter)
        {
            var loggedInUser = await userManager.GetUserAsync(User);

            // List result 
            if (User.IsInRole("Admin"))
            {
                model = await TicketViewModelAdmin(model);
            }
            else if (User.IsInRole("Developer"))
            {
                model = await TicketViewModelDeveloper(model, loggedInUser);
            }
            else
            {
                model = await TicketViewModelCustomer(model, loggedInUser);
            }

            if (User.IsInRole("Developer") || User.IsInRole("Admin"))
            {
                ViewData["Companies"] = new SelectList(_context.Companies, "Id", "CompanyName");
                ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name");
            }

            else if (User.IsInRole("Customer"))
            {
                //loggedInUser = await userManager.GetUserAsync(User);
                ViewData["ProjectId"] = new SelectList(_context.Projects.Where(g => g.CompanyId == loggedInUser.CompanyId), "Id", "Name");
            }

            // List all the result and not show Draft Status 
            model2 = await _context.Tickets.Include(t => t.AssignedUser).Include(t => t.CreatedUser).Include(t => t.Project)
                       .Where(s => s.Status != Status.Utkast)
                       .Select(s => new TicketIndexViewModel
                       {
                           Id = s.Id,
                           RefNo = s.RefNo,
                           Title = s.Title,
                           Status = s.Status,
                           ProjectName = s.Project.Name,
                           CompanyName = s.Project.Company.CompanyName,
                           CustomerPriority = s.CustomerPriority,

TicketManagementSystem/Views/ApplicationUsers/Delete.cshtml
@model TicketManagementSystem.Core.Models.ApplicationUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Radera</h1>


@if (@ViewBag.formhide == "Show")
{
    <h3>Är du säker på att du vill ta bort den här användaren?</h3>
}
else if (@ViewBag.formhide == "Hide")
{

    @if (@ViewBag.PageName == "Developer")
    {

        <p id="deletemsg"><b>Den här användaren kan inte raderas. Det finns några relaterade projekt till denna utvecklare.</b></p>
        <h3>Vill du fortfarande göra användaren inaktiv??</h3>
    }
    else
    {

        <p id="deletemsg"><b>Den här användaren kan inte raderas. Det finns relaterade ärende för den här användare.</b></p>
        <h3>Vill du fortfarande göra användaren inaktiv??</h3>

    }


}
else if (@ViewBag.formhide == "Admin")
{

    <p id="deletemsg"><b>Administratörsanvändaren kan inte raderas.</b></p>

}


<div>
    @*<h4>Användare</h4>*@
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.CompanyAbbr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    @if (@ViewBag.formhide == "Show")
    {
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" asp-route-name=@ViewData["PageName"] />
            <input type="submit" value="Radera" class="btn btn-danger" /> |
            <a asp-action="Index" asp-route-name=@ViewData["PageName"]>Tillbaka till listan</a>
        </form>
    }
    else
    {

<a asp-controller="ApplicationUsers" asp-action="InActive" asp-route-id="@Model.Id" asp-route-name=@ViewData["PageName"]> <button class="btn btn-danger">Inaktiv</button></a>  
        <a asp-action="Index" asp-route-name=@ViewData["PageName"]>Tillbaka till listan</a>

    }
    </div>

TicketManagementSystem/Views/ApplicationUsers/Details.cshtml
@model TicketManagementSystem.Core.Models.ApplicationUser

@{
    ViewData["Title"] = "Details";
}

    <h1>Detaljer</h1>

<div>
    @*<h4>Användare</h4>*@
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.CompanyAbbr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.CompanyAbbr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" asp-route-name=@ViewData["PageName"]>Redigera</a> |
    <a asp-action="Index" asp-route-name=@ViewData["PageName"]>Tillbaka till listan</a>
</div>

TicketManagementSystem/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<ApplicationUserwithRole>

@{
    ViewData["Title"] = "UsersIndex";
}

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">

        @if (@ViewBag.PageName == "Developer")
        {
            <a class="navbar-brand" asp-area="" asp-controller="ApplicationUsers" asp-action="Index" asp-route-name="Developer">
                <h1>
                    <p>Administratörer / Utvecklare</p>
                </h1>
            </a>
        }
        else
        {
            <a class="navbar-brand" asp-area="" asp-controller="ApplicationUsers" asp-action="Index" asp-route-name="Customer">
                <h1>
                    <p>Kundrepresentant</p>
                </h1>
            </a>

        }
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        @if (User.IsInRole("Admin"))
        {
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                @*<partial name="_LoginPartial" />*@
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Ärende</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Kunder</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Lösning</a>
                    </li>
                    @if (@ViewBag.PageName == "Developer")
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ApplicationUsers" asp-action="Index" asp-route-name="Customer">Kundrepresentant</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ApplicationUsers" asp-action="Index" asp-route-name="Developer">Administratörer / Utvecklare</a>
                        </li>
                    }



                </ul>
            </div>
        }
    </div>
</nav>


@*<p>
    <a asp-area="Identity" asp-page="/Account/Register">Register New @ViewData["PageName"]</a>
</p>*@
<table class="table table-striped table-hover">
    <thead class="text-primary">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.CompanyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.JobTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.PhoneNumber)
            </th>
            <th></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Company.CompanyAbbr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.JobTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.PhoneNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ApplicationUser.Id" asp-route-name=@ViewData["PageName"]>Redigera</a> |
                <a asp-action="Details" asp-route-id="@item.ApplicationUser.Id" asp-route-name=@ViewData["PageName"]>Detaljer</a> |
                <a asp-action="Delete" asp-route-id="@item.ApplicationUser.Id" asp-route-name=@ViewData["PageName"]>Radera</a>
            </td>
        </tr>
        }
    </tbody>
</table>